"""
Django settings for cntso project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os as _os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En prod, définir la var d'env SECRET_KEY avec une valeur aléatoire sûre.
SECRET_KEY = _os.environ.get(
    'SECRET_KEY',
    'django-insecure-q5yt_w9j0c%9b)6@g4cn@i#y%9c_#4ng!=^sximhzrars42jw_',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Défaut False. Surcharger via local_settings.py (DEBUG = True) en dev.
DEBUG = _os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost', '127.0.0.1', 'testserver',
    'cnt-so.org', 'www.cnt-so.org',
]

CSRF_TRUSTED_ORIGINS = [
    'https://cnt-so.org', 'https://www.cnt-so.org',
]

if DEBUG:
    ALLOWED_HOSTS += ['.ngrok-free.app', '.ngrok-free.dev', '.ngrok.io']
    CSRF_TRUSTED_ORIGINS += [
        'https://*.ngrok-free.app', 'https://*.ngrok-free.dev', 'https://*.ngrok.io',
    ]


# Application definition

INSTALLED_APPS = [
    # Wagtail
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.settings',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
    'wagtailseo',
    'wagtailmedia',
    'wagtail_2fa',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'hcaptcha',
    'wagtailcache',
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    # Apps locales
    'content',
    'cms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'cntso.middleware.BasicAuthMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'wagtail_2fa.middleware.VerifyUserPermissionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cntso.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'content.context_processors.menu_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cntso.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Envoi d'e-mails ────────────────────────────────────────────────────────────
# Par défaut en développement : affiche les e-mails dans la console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'ssl0.ovh.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'CNT-SO <newsletter@cnt-so.org>'
SERVER_EMAIL = 'newsletter@cnt-so.org'

# Délai entre chaque e-mail pour respecter les limites OVH (~200/heure)
NEWSLETTER_SEND_DELAY = 18  # secondes entre chaque envoi (200/h = 1 toutes les 18s)

# ── OVH Mailing Lists API ─────────────────────────────────────────────────────
OVH_APPLICATION_KEY    = _os.environ.get('OVH_APPLICATION_KEY', '')
OVH_APPLICATION_SECRET = _os.environ.get('OVH_APPLICATION_SECRET', '')
OVH_CONSUMER_KEY       = _os.environ.get('OVH_CONSUMER_KEY', '')
OVH_DOMAIN             = _os.environ.get('OVH_DOMAIN', 'cnt-so.info')

# ── Intégration cnt-adhesion ──────────────────────────────────────────────────
# Secret partagé pour vérifier les webhooks venant de cnt-adhesion
ADHESION_WEBHOOK_SECRET = _os.environ.get('ADHESION_WEBHOOK_SECRET', '')
# URL publique de l'app cnt-adhesion
ADHESION_BASE_URL = _os.environ.get('ADHESION_BASE_URL', 'https://adhesion.cnt-so.org')
# Mettre à True pour rediriger /adherer/<slug>/ vers la nouvelle app
ADHESION_USE_NEW_APP = _os.environ.get('ADHESION_USE_NEW_APP', 'false').lower() == 'true'

WAGTAIL_SITE_NAME = 'CNT-SO'
WAGTAILADMIN_BASE_URL = 'https://cnt-so.org'

# ── wagtail-2fa ───────────────────────────────────────────────────────────────
WAGTAIL_2FA_REQUIRED = False  # True = obligatoire pour tous les rédacteurs

# ── hCaptcha ──────────────────────────────────────────────────────────────────
# Clés de test (toujours valides en dev — remplacer en prod via local_settings.py)
# Créer un compte sur https://dashboard.hcaptcha.com/
HCAPTCHA_SITEKEY = _os.environ.get('HCAPTCHA_SITEKEY', '10000000-ffff-ffff-ffff-000000000001')
HCAPTCHA_SECRET = _os.environ.get('HCAPTCHA_SECRET', '0x0000000000000000000000000000000000000000')

# ── wagtail-cache ─────────────────────────────────────────────────────────────
WAGTAILCACHE_CACHE = 'default'
WAGTAILCACHE_TIMEOUT = 3600

# Recherche Wagtail — PostgreSQL FTS en prod, base de données SQLite en dev
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.database',
    }
}

# ── Headers de sécurité ────────────────────────────────────────────────────────
# Empêche le navigateur de deviner le type MIME (MIME sniffing)
SECURE_CONTENT_TYPE_NOSNIFF = True
# Protection XSS navigateur legacy
SECURE_BROWSER_XSS_FILTER = True
# Limite les ressources dans les iframes (Clickjacking) — déjà géré par XFrameOptionsMiddleware
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Surcharge par local_settings.py (credentials, DEBUG, etc.) — jamais commité
try:
    from .local_settings import *  # noqa
    from .local_settings import INSTALLED_APPS_EXTRA  # noqa
    INSTALLED_APPS = INSTALLED_APPS + INSTALLED_APPS_EXTRA
except (ImportError, NameError):
    pass

# ── Durcissement production ────────────────────────────────────────────────────
# Après l'import de local_settings pour connaître la valeur finale de DEBUG.
if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "SECRET_KEY absente en production : définir la variable "
            "d'environnement SECRET_KEY (ou la surcharger dans local_settings.py)."
        )
    # Cookies uniquement sur HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # nginx doit transmettre X-Forwarded-Proto pour que Django voie le HTTPS
    # (nécessaire à l'émission du header HSTS derrière le reverse proxy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 2592000  # 30 jours — la redirection HTTP→HTTPS reste gérée par nginx
