"""
Django settings for cntso project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os as _os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En prod, définir la var d'env SECRET_KEY avec une valeur aléatoire sûre.
SECRET_KEY = _os.environ.get(
    'SECRET_KEY',
    'django-insecure-q5yt_w9j0c%9b)6@g4cn@i#y%9c_#4ng!=^sximhzrars42jw_',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Défaut False. Surcharger via local_settings.py (DEBUG = True) en dev.
DEBUG = _os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost', '127.0.0.1', 'testserver',
    'cnt-so.org', 'www.cnt-so.org',
]

CSRF_TRUSTED_ORIGINS = [
    'https://cnt-so.org', 'https://www.cnt-so.org',
]

if DEBUG:
    ALLOWED_HOSTS += ['.ngrok-free.app', '.ngrok-free.dev', '.ngrok.io']
    CSRF_TRUSTED_ORIGINS += [
        'https://*.ngrok-free.app', 'https://*.ngrok-free.dev', 'https://*.ngrok.io',
    ]


# Application definition

INSTALLED_APPS = [
    # Wagtail
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.settings',
    'wagtail.embeds',
    'wagtail.sites',
    'content.apps.CustomUsersAppConfig',  # wagtail.users + champ Syndicat sur les formulaires
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    'modelcluster',
    'taggit',
    'wagtailseo',
    'wagtailmedia',
    'wagtail_2fa',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'hcaptcha',
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    # Apps locales
    'content',
    'cms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'cntso.middleware.BasicAuthMiddleware',
    'cntso.middleware.SectionDomainMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'wagtail_2fa.middleware.VerifyUserPermissionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cntso.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'content.context_processors.menu_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cntso.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Tests ─────────────────────────────────────────────────────────────────────
# Parallèle par défaut : la suite passe d'environ cinq minutes à une (mesuré le
# 18/08/2026). `--parallel 1` reste possible pour déboguer.
TEST_RUNNER = 'cntso.test_runner.RunnerParallele'

# ── Envoi d'e-mails ────────────────────────────────────────────────────────────
# Par défaut en développement : affiche les e-mails dans la console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'ssl0.ovh.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'CNT-SO <newsletter@cnt-so.org>'
SERVER_EMAIL = 'newsletter@cnt-so.org'
# Domaine du Message-ID des courriels sortants. Sans lui, Django prend le nom
# d'hôte de la machine — « cnt-so » en production, qui n'est pas un domaine
# valide et vaut un point de suspicion aux filtres antispam. Voir
# content.apps._fixer_le_domaine_des_message_id.
EMAIL_MESSAGE_ID_DOMAIN = _os.environ.get('EMAIL_MESSAGE_ID_DOMAIN', 'cnt-so.org')
# Adresse de réponse des courriels de la newsletter : « newsletter@ » n'est
# relevée par personne, et un expéditeur sans réponse possible est un signal
# négatif de plus.
NEWSLETTER_REPLY_TO = _os.environ.get('NEWSLETTER_REPLY_TO', 'contact@cnt-so.org')
# Destinataire de secours des formulaires de contact sans e-mail configuré
DEFAULT_CONTACT_EMAIL = 'contact@cnt-so.org'

# Délai entre chaque e-mail pour respecter les limites OVH (~200/heure)
NEWSLETTER_SEND_DELAY = 18  # secondes entre chaque envoi (200/h = 1 toutes les 18s)

# ── OVH Mailing Lists API ─────────────────────────────────────────────────────
OVH_APPLICATION_KEY    = _os.environ.get('OVH_APPLICATION_KEY', '')
OVH_APPLICATION_SECRET = _os.environ.get('OVH_APPLICATION_SECRET', '')
OVH_CONSUMER_KEY       = _os.environ.get('OVH_CONSUMER_KEY', '')
OVH_DOMAIN             = _os.environ.get('OVH_DOMAIN', 'cnt-so.info')
# Plafond d'abonnés par liste : limite dure OVH = 5000, marge de sécurité.
# Quand la 1re liste atteint ce seuil, les nouveaux abonnés vont sur la suivante
# du champ ovh_mailing_list (ex. « news,news2 » — ajouter news3 suffit à étendre).
OVH_LIST_CAP           = int(_os.environ.get('OVH_LIST_CAP', 4900))

# ── Intégration cnt-adhesion ──────────────────────────────────────────────────
# Secret partagé pour vérifier les webhooks venant de cnt-adhesion
ADHESION_WEBHOOK_SECRET = _os.environ.get('ADHESION_WEBHOOK_SECRET', '')
# URL publique de l'app cnt-adhesion
ADHESION_BASE_URL = _os.environ.get('ADHESION_BASE_URL', 'https://adhesion.cnt-so.org')
# Mettre à True pour rediriger /adherer/<slug>/ vers la nouvelle app
ADHESION_USE_NEW_APP = _os.environ.get('ADHESION_USE_NEW_APP', 'false').lower() == 'true'

WAGTAIL_SITE_NAME = 'CNT-SO'
WAGTAILADMIN_BASE_URL = 'https://cnt-so.org'
# Origine publique du site principal — utilisée par les domaines de fédérations
# pour renvoyer vers le site confédéral. Tant que la bascule DNS n'est pas faite,
# la prod doit la surcharger avec https://newsite.cnt-so.org (env ou local_settings).
MAIN_SITE_BASE_URL = _os.environ.get('MAIN_SITE_BASE_URL', WAGTAILADMIN_BASE_URL)

# ── wagtail-2fa ───────────────────────────────────────────────────────────────
WAGTAIL_2FA_REQUIRED = False  # True = obligatoire pour tous les rédacteurs

# Pas de circuit d'approbation : les rédacteurs publient directement
# (le brouillon reste disponible comme état de travail). Le workflow Wagtail
# par défaut « Moderators approval » envoyait les soumissions dans le vide.
WAGTAIL_WORKFLOW_ENABLED = False

# Pas d'annotation en marge des articles.
#
# Wagtail pose une bulle « commentaire » sur CHAQUE champ et CHAQUE bloc :
# 32 sur un écran d'article ordinaire, plus un panneau latéral. Ce décor
# vaudrait son prix si quelqu'un s'en servait — la base en compte 0 pour
# 1710 articles, et il n'y a pas de circuit d'approbation
# (WAGTAIL_WORKFLOW_ENABLED ci-dessus) où un modérateur annoterait une
# relecture. On paie donc l'encombrement sans la fonction (Arnaud, 31/08/2026).
#
# Le jour où un circuit de relecture entre syndicats se met en place, remettre
# cette ligne à True suffit : rien d'autre n'en dépend.
WAGTAILADMIN_COMMENTS_ENABLED = False

# ── hCaptcha ──────────────────────────────────────────────────────────────────
# Clés de test (toujours valides en dev — remplacer en prod via local_settings.py)
# Créer un compte sur https://dashboard.hcaptcha.com/
HCAPTCHA_SITEKEY = _os.environ.get('HCAPTCHA_SITEKEY', '10000000-ffff-ffff-ffff-000000000001')
HCAPTCHA_SECRET = _os.environ.get('HCAPTCHA_SECRET', '0x0000000000000000000000000000000000000000')

# ── Caches ────────────────────────────────────────────────────────────────────
#
# `default` reste le cache local du processus : c'est celui des pages
# (wagtail-cache), et chaque worker gunicorn peut garder le sien.
#
# `limites` doit au contraire être PARTAGÉ entre les trois workers : il porte le
# compteur d'inscriptions à la newsletter par adresse IP. Dans un cache local,
# la limite de 3 par heure en aurait valu 9, et serait repartie de zéro à chaque
# redémarrage — une passoire face au botnet de juillet-août 2026.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'limites': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_limites',
    },
}

# ── Pas de cache de pages, et c'est délibéré ──────────────────────────────────
# `wagtail-cache` était installé et réglé (`WAGTAILCACHE_CACHE`,
# `WAGTAILCACHE_TIMEOUT = 3600`) mais ses middlewares n'ont jamais été branchés :
# aucune page n'a jamais été mise en cache. Les réglages et la documentation
# décrivaient un dispositif inexistant (audit du 27/08/2026).
#
# Le brancher tel quel aurait été pire que de s'en passer. La production fait
# tourner **trois workers gunicorn** et le cache visé était `LocMemCache`, qui
# vit dans le processus : trois caches indépendants, donc un « vider le cache »
# depuis /cms/ ne purgerait qu'un worker sur trois. Un rédacteur corrigerait un
# article, purgerait, rechargerait, et verrait l'ancienne version deux fois sur
# trois pendant une heure. Rien ne ruine plus vite la confiance dans un CMS.
#
# Et il n'y a rien à gagner : 615 requêtes par jour, pages rendues en 30 à 70 ms.
#
# Le jour où il en faudrait un, la base est déjà là : le cache `limites`
# ci-dessous utilise `DatabaseCache`, partagé entre workers et sans service
# supplémentaire à installer. La clé de Django inclut l'hôte
# (`build_absolute_uri`), donc les domaines autonomes ne se mélangeraient pas.

# Recherche Wagtail — PostgreSQL FTS en prod, base de données SQLite en dev
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.database',
    }
}

# ── Headers de sécurité ────────────────────────────────────────────────────────
# Empêche le navigateur de deviner le type MIME (MIME sniffing)
SECURE_CONTENT_TYPE_NOSNIFF = True
# Protection XSS navigateur legacy
SECURE_BROWSER_XSS_FILTER = True
# Limite les ressources dans les iframes (Clickjacking) — déjà géré par XFrameOptionsMiddleware
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ── Logging ────────────────────────────────────────────────────────────────────
# Erreurs et warnings dans logs/django.log (rotation 5 Mo × 3) + stderr
# (repris par supervisor dans /var/log/cntso.log en prod).
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Une erreur 500 part par courriel, plafonnée à une par heure et par
        # signature (voir cntso.alertes). Sans elle, une panne reste dans un
        # fichier que personne ne lit : les 43 adresses d'article en erreur
        # ont duré du 26/08 au 03/09/2026 sans que rien ne le signale.
        'admins': {
            'class': 'cntso.alertes.AlerteLimitee',
            'level': 'ERROR',
            'include_html': True,
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file', 'console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Explicite plutôt que de compter sur la configuration par défaut de
        # Django : ce projet redéfinit LOGGING, et se reposer sur une fusion
        # implicite rendrait l'alerte silencieusement inopérante le jour où
        # quelqu'un touche à ce bloc.
        'django.request': {
            'handlers': ['admins', 'file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Destinataires des alertes d'erreur. Adresse dédiée créée par Arnaud le
# 04/09/2026. Vide par défaut : en développement et pendant les tests, aucun
# courriel ne part.
# `if adr.strip()` : une entrée sans adresse est REJETÉE, pas gardée.
# Le 04/09/2026, systemd a coupé `Environment=DJANGO_ADMINS=Technique CNT-SO:…`
# sur l'espace du nom ; il ne restait que « Technique », d'où un couple
# ('Technique', '') — et l'alerte partait « à personne » en annonçant un
# succès. Un système d'alerte qui échoue en silence est pire que pas d'alerte.
ADMINS = [
    (nom.strip() or 'Technique', adr.strip())
    for nom, _, adr in (
        couple.partition(':')
        for couple in _os.environ.get('DJANGO_ADMINS', '').split(',')
        if couple.strip()
    )
    if adr.strip()
]

# Surcharge par local_settings.py (credentials, DEBUG, etc.) — jamais commité
try:
    from .local_settings import *  # noqa
    from .local_settings import INSTALLED_APPS_EXTRA  # noqa
    INSTALLED_APPS = INSTALLED_APPS + INSTALLED_APPS_EXTRA
except (ImportError, NameError):
    pass

# Domaines autonomes des fédérations (chantier domaines) — appliqués après
# local_settings pour valoir quelle que soit la valeur finale des listes.
# En prod : FEDERATION_DOMAINS="stucs.cnt-so.org,numerique.cnt-so.org,…"
FEDERATION_DOMAINS = [
    d.strip().lower()
    for d in _os.environ.get('FEDERATION_DOMAINS', '').split(',') if d.strip()
]
ALLOWED_HOSTS += [d for d in FEDERATION_DOMAINS if d not in ALLOWED_HOSTS]
CSRF_TRUSTED_ORIGINS += [
    o for o in (f'https://{d}' for d in FEDERATION_DOMAINS)
    if o not in CSRF_TRUSTED_ORIGINS
]

# ── Base PostgreSQL pour l'intégration continue ───────────────────────────────
# Les tests tournent sur SQLite en développement, la production sur PostgreSQL.
# Cet écart n'est pas cosmétique : un tri décroissant place les NULL EN TÊTE en
# PostgreSQL et EN QUEUE en SQLite. Trois articles d'essai sans date se sont
# ainsi retrouvés aux trois premières places du flux RSS du STUCS, sans qu'aucun
# test ne le voie (15/08/2026).
#
# Posé APRÈS l'import de `local_settings` pour primer en CI, où ce fichier
# n'existe pas. En production, `local_settings.py` définit déjà PostgreSQL et
# `CI_POSTGRES` n'y est pas : ce bloc y reste inerte.
if _os.environ.get('CI_POSTGRES'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _os.environ.get('POSTGRES_DB', 'cntso_ci'),
            'USER': _os.environ.get('POSTGRES_USER', 'cntso'),
            'PASSWORD': _os.environ.get('POSTGRES_PASSWORD', 'cntso'),
            'HOST': _os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': _os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


# PostgreSQL exige `django.contrib.postgres` : l'index de recherche de Wagtail
# (`wagtailsearch.IndexEntry`) utilise SearchVectorField et GinIndex, que Django
# refuse sans cette application — six erreurs `postgres.E005` et le site ne
# démarre pas.
#
# La production l'avait, mais par `local_settings.py`, un fichier non versionné :
# `settings.py` seul ne savait donc pas tourner sur la base de production. Le
# défaut est apparu en montant l'intégration continue (03/09/2026), qui n'a pas
# ce fichier. Piloté par le moteur, il vaut désormais pour les deux.
if DATABASES['default']['ENGINE'].endswith('postgresql'):
    if 'django.contrib.postgres' not in INSTALLED_APPS:
        INSTALLED_APPS = list(INSTALLED_APPS) + ['django.contrib.postgres']


# ── Durcissement production ────────────────────────────────────────────────────
# Après l'import de local_settings pour connaître la valeur finale de DEBUG.
if not DEBUG:
    if SECRET_KEY.startswith('django-insecure-'):
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "SECRET_KEY absente en production : définir la variable "
            "d'environnement SECRET_KEY (ou la surcharger dans local_settings.py)."
        )
    # Cookies uniquement sur HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # nginx doit transmettre X-Forwarded-Proto pour que Django voie le HTTPS
    # (nécessaire à l'émission du header HSTS derrière le reverse proxy)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 2592000  # 30 jours — la redirection HTTP→HTTPS reste gérée par nginx
