services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./cntso/local_settings.py:/app/cntso/local_settings.py
    restart: unless-stopped
