# Generated by Django 6.0.2 on 2026-05-28 17:29

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Page d'accueil",
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 4), ('gallery', 8), ('file', 11), ('quote', 14), ('embed', 15), ('html', 16)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Texte', 'template': 'cms/blocks/rich_text_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite'), ('full', 'Pleine largeur')], 'label': 'Alignement'}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Images'}), 7: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Colonnes', 'max_value': 6, 'min_value': 1}), 8: ('wagtail.blocks.StructBlock', [[('images', 6), ('columns', 7)]], {}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Titre affiché', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('document', 9), ('title', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Citation'}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Source / Auteur', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 12), ('citation', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Vidéo / iFrame'}), 16: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Utilisé pour le contenu importé qui ne peut pas être converti.', 'label': 'HTML brut (import legacy)'})})),
                ('excerpt', models.TextField(blank=True, verbose_name='Extrait')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Article mis en avant (sticky)')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='Auteur')),
                ('publication_date', models.DateTimeField(blank=True, help_text='Date originale (WordPress / import)', null=True, verbose_name='Date de publication')),
                ('section_slug', models.SlugField(blank=True, help_text='Slug dénormalisé de la SectionPage parente', max_length=100)),
                ('legacy_article_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_wp_id', models.IntegerField(blank=True, null=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_articles', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur auteur')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image mise en avant')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CmsArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.articlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='cms_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.CmsArticleTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='CmsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('section_slug', models.SlugField(blank=True, default='principal', help_text='Slug de la SectionPage à laquelle cette catégorie appartient', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, help_text="ID content.Category d'origine", null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.cmscategory')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
                'unique_together': {('section_slug', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='articlepage',
            name='cms_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='articles', to='cms.cmscategory', verbose_name='Catégories'),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 4), ('gallery', 8), ('file', 11), ('quote', 14), ('embed', 15), ('html', 16)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Texte', 'template': 'cms/blocks/rich_text_block.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Gauche'), ('center', 'Centre'), ('right', 'Droite'), ('full', 'Pleine largeur')], 'label': 'Alignement'}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Images'}), 7: ('wagtail.blocks.IntegerBlock', (), {'default': 3, 'label': 'Colonnes', 'max_value': 6, 'min_value': 1}), 8: ('wagtail.blocks.StructBlock', [[('images', 6), ('columns', 7)]], {}), 9: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Titre affiché', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('document', 9), ('title', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'label': 'Citation'}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Source / Auteur', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 12), ('citation', 13)]], {}), 15: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Vidéo / iFrame'}), 16: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Utilisé pour le contenu importé qui ne peut pas être converti.', 'label': 'HTML brut (import legacy)'})})),
                ('excerpt', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('section_slug', models.SlugField(blank=True, max_length=100)),
                ('legacy_page_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Page de contenu',
                'verbose_name_plural': 'Pages de contenu',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section_type', models.CharField(choices=[('main', 'Site principal'), ('regional', 'Union régionale'), ('sectoral', 'Syndicat sectoriel')], default='regional', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('agenda_url', models.URLField(blank=True)),
                ('legacy_site_slug', models.SlugField(blank=True, max_length=100)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Section (syndicat)',
                'verbose_name_plural': 'Sections (syndicats)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
