# Generated by Django 6.0.2 on 2026-05-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Adresse email qui reçoit les messages du formulaire de contact', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='wp_blog_id',
            field=models.IntegerField(blank=True, help_text='Identifiant blog WordPress (import legacy)', null=True, unique=True, verbose_name='WP blog_id'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='wp_path',
            field=models.CharField(blank=True, help_text='Path WordPress legacy (ex: /normandie/)', max_length=100, verbose_name='Path WordPress'),
        ),
    ]
