# Generated by Django 6.0.2 on 2026-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sectionpage_contact_email_wp_blog_id_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='framaform_url',
            field=models.URLField(blank=True, help_text='Ex: https://framaforms.org/adherer-au-stucs-...', verbose_name='URL Framaform adhésion'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='linkstack_url',
            field=models.URLField(blank=True, help_text='Ex: https://linkstack.fr/@stucs_cntso', verbose_name='URL Linkstack'),
        ),
    ]
