# Generated by Django 6.0.2 on 2026-06-02 12:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_sectionpage_linkstack_framaform'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='agenda_text',
            field=wagtail.fields.StreamField([('contenu', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Contenu'})}, help_text='Événements, dates, calendrier — éditable librement', verbose_name='Agenda'),
        ),
    ]
