# Generated by Django 6.0.2 on 2026-06-02 12:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sectionpage_agenda_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='intro_text',
            field=wagtail.fields.StreamField([('contenu', 0), ('liste', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Contenu'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Liste à puces'})}, help_text="Affiché sur la page d'accueil du sous-site après l'accroche", verbose_name='Présentation + revendications (page accueil)'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='rejoindre_text',
            field=wagtail.fields.StreamField([('contenu', 0), ('liste', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Contenu'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Liste à puces'})}, help_text="Texte de la page d'adhésion (pourquoi, comment ça marche…)", verbose_name='Page Nous rejoindre'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='agenda_text',
            field=wagtail.fields.StreamField([('contenu', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Contenu'})}, help_text='Événements, dates, calendrier', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='description',
            field=models.TextField(blank=True, help_text="Texte court affiché sous le titre en page d'accueil du sous-site", verbose_name='Description / accroche'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='framaform_url',
            field=models.URLField(blank=True, verbose_name='URL Framaform adhésion'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='linkstack_url',
            field=models.URLField(blank=True, verbose_name='URL Linkstack'),
        ),
    ]
