# Generated by Django 6.0.2 on 2026-06-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_sectionpage_intro_rejoindre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin (optionnel)')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Heure (optionnel)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, help_text="Lien vers plus d'infos", verbose_name='Lien (optionnel)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cms.sectionpage', verbose_name='Section / syndicat')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date', 'time'],
            },
        ),
    ]
