# Generated by Django 6.0.2 on 2026-06-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_articlepage_canonical_url_articlepage_og_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalSectionPage',
            fields=[
            ],
            options={
                'verbose_name': 'Union régionale',
                'verbose_name_plural': 'Unions régionales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sectionpage',),
        ),
        migrations.CreateModel(
            name='SectoralSectionPage',
            fields=[
            ],
            options={
                'verbose_name': 'Syndicat sectoriel',
                'verbose_name_plural': 'Syndicats sectoriels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cms.sectionpage',),
        ),
    ]
