# Generated by Django 6.0.2 on 2026-06-11 08:53

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_regional_sectoral_proxy_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.articlepage', verbose_name='Article')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='cms.sectionpage')),
            ],
            options={
                'verbose_name': 'Article du carrousel',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
