# Generated by Django 6.0.2 on 2026-06-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_carousel_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='in_carousel',
            field=models.BooleanField(default=False, help_text='Ajoute cet article au carrousel mis en avant (syndicats sectoriels uniquement, 5 max)', verbose_name="Dans le carrousel de l'accueil"),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Place cet article en position vedette sur la page d'accueil de son syndicat", verbose_name="Mis en avant sur l'accueil du syndicat"),
        ),
    ]
