# Generated by Django 6.0.2 on 2026-06-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_articlepage_in_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_on_conf',
            field=models.BooleanField(default=False, help_text="Affiche cet article dans la section vedette de la page d'accueil de la confédération (tous syndicats)", verbose_name='Mettre en avant sur la confédération'),
        ),
    ]
