# Generated by Django 6.0.2 on 2026-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_articlepage_featured_on_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='social_discord',
            field=models.URLField(blank=True, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='social_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='social_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='social_mastodon',
            field=models.URLField(blank=True, verbose_name='Mastodon'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='social_telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='social_twitter',
            field=models.URLField(blank=True, verbose_name='Twitter / X'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='social_youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
