# Generated by Django 6.0.2 on 2026-06-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_sectionpage_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='social_bluesky',
            field=models.URLField(blank=True, verbose_name='BlueSky'),
        ),
    ]
