# Generated by Django 6.0.2 on 2026-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_sectionpage_social_bluesky'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
