# Generated by Django 6.0.2 on 2026-06-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_event_geocoords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='ovh_mailing_list',
            field=models.CharField(blank=True, help_text='Nom de la liste sur cnt-so.info, ex: actu-stucs-cntso', max_length=100, verbose_name='Liste mail OVH (newsletter)'),
        ),
    ]
