# Generated by Django 6.0.2 on 2026-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_sectionpage_ovh_mailing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='ovh_mailing_list',
            field=models.CharField(blank=True, help_text='Noms des listes sur cnt-so.info, séparés par des virgules', max_length=500, verbose_name='Liste(s) mail OVH (newsletter)'),
        ),
    ]
