# Generated by Django 6.0.7 on 2026-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_ovh_mailing_list_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='custom_domain',
            field=models.CharField(blank=True, default='', help_text="Nom d'hôte nu, ex. stucs.cnt-so.org — vide = le sous-site reste servi sous cnt-so.org/<slug>/ (comportement actuel)", max_length=253, verbose_name='Domaine autonome'),
        ),
    ]
