# Generated by Django 6.0.7 on 2026-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_sectionpage_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='social_linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
    ]
