# Generated by Django 6.0.7 on 2026-08-15 12:01

from django.db import migrations, models


def cocher_ceux_qui_ont_deja_leur_banque(apps, schema_editor):
    """Aligne la case sur la réalité au moment de la migration.

    Trois syndicats ont déjà leur catégorie « banque-dimage » (principal,
    numerique, stucs). Sans ce pas, la case serait décochée partout et ils
    perdraient le lien vers leur propre banque au profit de la confédérale.
    """
    SectionPage = apps.get_model('cms', 'SectionPage')
    CmsCategory = apps.get_model('cms', 'CmsCategory')
    proprietaires = set(
        CmsCategory.objects.filter(slug='banque-dimage')
        .values_list('section_slug', flat=True))
    for section in SectionPage.objects.all():
        slugs = {section.slug, section.legacy_site_slug or section.slug}
        if slugs & proprietaires:
            section.banque_images_propre = True
            section.save(update_fields=['banque_images_propre'])


def decocher(apps, schema_editor):
    apps.get_model('cms', 'SectionPage').objects.update(
        banque_images_propre=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_sectionpage_social_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='banque_images_propre',
            field=models.BooleanField(default=False, help_text="Coché : le bloc « Notre banque d'images » de la barre latérale mène à la banque de ce syndicat. Décoché : il renvoie à celle de la confédération.", verbose_name="Banque d'images propre à ce syndicat"),
        ),
        migrations.RunPython(cocher_ceux_qui_ont_deja_leur_banque, decocher),
    ]
