# Generated by Django 6.0.7 on 2026-08-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_articlepage_body_alter_contentpage_body_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='author_user',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='excerpt',
            field=models.TextField(blank=True, help_text="Le texte de présentation sur les listes et dans la newsletter. Laissé vide, il est repris du début de l'article.", verbose_name='Extrait'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text="⚠️ Sans image, votre article passe DERRIÈRE tous les articles illustrés de sa rubrique, quelle que soit sa date — les listes du site classent les articles illustrés d'abord. Un article publié aujourd'hui sans image arrive en bas de page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image mise en avant'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Réservé aux articles du site confédéral : place l'article en position vedette sur cnt-so.org. Pour mettre un article en avant sur l'accueil de VOTRE syndicat, utilisez « Dans le carrousel de l'accueil ».", verbose_name="Mis en avant sur l'accueil de la confédération"),
        ),
    ]
