# Generated by Django 6.0.7 on 2026-08-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_remove_articlepage_author_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='feed_etag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='feed_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='feed_url',
            field=models.URLField(blank=True, help_text="Uniquement pour un syndicat hébergé ailleurs : ses articles remontent alors dans « Les nouvelles du réseau » sur l'accueil confédéral. Sur un WordPress, laissez vide — le flux est déduit de l'adresse du site (…/feed/).", verbose_name='URL du flux RSS / Atom'),
        ),
    ]
