# Generated by Django 6.0.7 on 2026-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_sectionpage_feed_etag_sectionpage_feed_last_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='ovh_liste_inscription',
            field=models.CharField(blank=True, help_text="Les personnes qui s'inscrivent depuis le site atterrissent sur cette liste, pour rester distinctes des adresses héritées. Elle doit aussi figurer ci-dessus pour recevoir la newsletter. Vide : première liste non pleine.", max_length=100, verbose_name="Liste d'arrivée des inscrits du site"),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='ovh_mailing_list',
            field=models.CharField(blank=True, help_text='Noms des listes sur cnt-so.info, séparés par des virgules. La newsletter part à TOUTES ces listes.', max_length=500, verbose_name='Liste(s) mail OVH (newsletter)'),
        ),
    ]
