# Generated by Django 6.0.7 on 2026-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_sectionpage_ovh_liste_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='newsletter_active',
            field=models.BooleanField(default=False, help_text="Décoché : aucun encart d'inscription n'apparaît sur le site et le syndicat ne peut pas envoyer de lettre. Seule la confédération diffuse une newsletter publique — les autres listes OVH sont des listes de travail internes, réservées aux adhérent·es. Cochez pour rendre la newsletter à ce syndicat : il faudra aussi lui rattacher une liste ci-dessous.", verbose_name='Proposer la newsletter sur ce site'),
        ),
    ]
