# Generated by Django 6.0.7 on 2026-08-17 17:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_newsletter_conf_seule'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='rejoindre_accroche',
            field=models.CharField(blank=True, default="Remplis le formulaire d'adhésion en ligne, paiement de la cotisation inclus.", help_text='Sous le titre « Adhérer à … », en haut de la page. Vide : aucune phrase.', max_length=300, verbose_name="Bandeau : phrase d'accroche"),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='rejoindre_atouts',
            field=models.TextField(blank=True, default='Formulaire en ligne, 5 minutes\nCotisation libre et solidaire\nUn·e militant·e te recontacte pour finaliser', help_text="Une ligne par argument, chacun précédé d'une coche. Vide : aucun argument affiché.", verbose_name='Bandeau : arguments'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='rejoindre_bouton',
            field=models.CharField(blank=True, default='Adhérer maintenant', help_text="Vidé, le bouton reprend « Adhérer maintenant » : il ne peut pas disparaître, c'est le seul chemin vers l'adhésion.", max_length=60, verbose_name='Bandeau : libellé du bouton'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='rejoindre_text',
            field=wagtail.fields.StreamField([('contenu', 0), ('liste', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'strikethrough', 'h2', 'h3', 'h4', 'h5', 'ol', 'ul', 'link', 'blockquote', 'hr'], 'label': 'Contenu'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Item'}), 2: ('wagtail.blocks.ListBlock', (1,), {'label': 'Liste à puces'})}, help_text="Corps de la page d'adhésion. Chaque bloc s'affiche dans son propre encadré : un bloc « pourquoi adhérer », un bloc « comment ça marche »…", verbose_name='Page Nous rejoindre'),
        ),
    ]
