# Generated by Django 6.0.7 on 2026-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_rejoindre_texte_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='fiche_pratique',
            field=models.BooleanField(default=False, help_text="Ajoute sous l'article un bouton « Télécharger le tract » : une version A4 en couleur, prête à imprimer et à afficher au travail. Pour les articles qui servent d'outil — droits, procédures, mémentos — pas pour une actualité.", verbose_name='Fiche pratique — téléchargeable en tract'),
        ),
    ]
