# Generated by Django 6.0.8 on 2026-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_articlepage_body_alter_contentpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured_on_conf',
            field=models.BooleanField(default=False, help_text="Place l'article en vedette sur l'accueil de cnt-so.org, quel que soit le syndicat qui l'a écrit. Réservé aux chefs.", verbose_name='À la une de la confédération'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='in_carousel',
            field=models.BooleanField(default=False, help_text="Place l'article dans le carrousel de l'accueil de VOTRE site — pas celui de la confédération. Syndicats sectoriels et régionaux, 5 articles au maximum.", verbose_name='Au carrousel de mon syndicat'),
        ),
    ]
