# Generated by Django 6.0.8 on 2026-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_remove_articlepage_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='featured_on_conf',
            field=models.BooleanField(default=False, help_text="Place l'article dans le diaporama d'accueil de cnt-so.org, quel que soit le syndicat qui l'a écrit. Réservé aux chefs.", verbose_name='À la une de la confédération'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='in_carousel',
            field=models.BooleanField(default=False, help_text="Place l'article dans le diaporama en haut de l'accueil de VOTRE site — c'est la une du syndicat. 5 articles au maximum ; au-delà, le plus ancien reste en place.", verbose_name='À la une de mon syndicat'),
        ),
    ]
