# Generated by Django 6.0.8 on 2026-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_alter_articlepage_featured_on_conf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='in_carousel',
            field=models.BooleanField(default=False, help_text="Place l'article EN TÊTE du diaporama de VOTRE accueil et l'y maintient. Vos articles récents illustrés y passent déjà tout seuls : cochez surtout pour y ramener un article plus ancien. 5 au maximum. Décoché, l'article n'est pas perdu — il redescend dans la page.", verbose_name='À la une de mon syndicat'),
        ),
    ]
