# Generated by Django 6.1.1 on 2026-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_alter_articlepage_in_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='in_manchette',
            field=models.BooleanField(default=False, help_text="Place l'article EN TÊTE de la manchette de VOTRE accueil — les cartes situées sous le diaporama. Même principe : les récents illustrés la remplissent tout seuls, cocher sert à y maintenir un article. 6 au maximum. Un article déjà au diaporama n'y est pas repris deux fois.", verbose_name='À la une de mon syndicat'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='in_carousel',
            field=models.BooleanField(default=False, help_text="Place l'article EN TÊTE du diaporama de VOTRE accueil — le grand bandeau qui défile — et l'y maintient. Vos articles récents illustrés y passent déjà tout seuls : cochez surtout pour y ramener un article plus ancien. 5 au maximum. Décoché, l'article n'est pas perdu — il redescend dans la page.", verbose_name='Diaporama de mon syndicat'),
        ),
    ]
