# Generated by Django 6.1.1 on 2026-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_articlepage_in_manchette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='adhesion_en_ligne',
            field=models.BooleanField(default=False, help_text="Coché : le bouton « Adhérer » mène au formulaire de l'application d'adhésion (adhesion.cnt-so.org), avant tout Framaform. Ne cocher qu'une fois le syndicat ouvert dans l'application : sinon le bouton mène à une erreur.", verbose_name='Adhésion en ligne ouverte'),
        ),
    ]
