# Generated by Django 6.1.1 on 2026-09-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_sectionpage_adhesion_en_ligne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='rejoindre_atouts',
            field=models.TextField(blank=True, default='Formulaire en ligne, 5 minutes\nCotisation solidaire\nUn·e militant·e te recontacte pour finaliser', help_text="Une ligne par argument, chacun précédé d'une coche. Vide : aucun argument affiché.", verbose_name='Bandeau : arguments'),
        ),
    ]
