# Generated by Django 6.1.1 on 2026-09-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_rejoindre_atouts_sans_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='ovh_listes_gerees',
            field=models.TextField(blank=True, help_text="Listes que ce syndicat peut consulter et modifier depuis « Listes mails », SANS jamais recevoir la newsletter. Séparées par des virgules. Sert aux listes de travail que personne d'autre ne gère.", verbose_name='Listes OVH gérées ici (hors newsletter)'),
        ),
    ]
