# Generated by Django 6.1.1 on 2026-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_sectionpage_ovh_listes_gerees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='in_manchette',
            field=models.BooleanField(default=False, help_text="Place l'article EN TÊTE de la manchette de VOTRE accueil — les cartes situées sous le diaporama. Même principe : les récents illustrés la remplissent tout seuls, cocher sert à y maintenir un article. 6 au maximum, le plus ancien coché laissant sa place. Coché, il y figure même s'il est aussi au diaporama.", verbose_name='À la une de mon syndicat'),
        ),
    ]
