# Generated by Django 6.1.1 on 2026-09-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_aide_une_et_diaporama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmscategory',
            name='slug',
            field=models.SlugField(blank=True, help_text="La fin de l'adresse de la page de la catégorie. Laissez vide : elle est fabriquée à partir du nom. Pas d'adresse web ici — pour mettre la catégorie dans un menu, choisissez « Catégorie du site » dans le menu.", max_length=200, verbose_name='Adresse'),
        ),
    ]
