# Generated by Django 6.1.1 on 2026-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_slug_categorie_facultatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='page_maintenance',
            field=models.BooleanField(default=False, help_text='Cochée, un site dépublié affiche « site en maintenance, on revient bientôt » au lieu de renvoyer à la confédération. Sans effet tant que le site est publié : cochez, publiez, puis dépubliez le site.', verbose_name='Page de maintenance quand le site est dépublié'),
        ),
    ]
