# Generated by Django 6.1.1 on 2026-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_page_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='in_manchette_conf',
            field=models.BooleanField(default=False, help_text="Place l'article en tête de la manchette de cnt-so.org — les cartes situées sous le diaporama —, quel que soit le syndicat qui l'a écrit. 6 au maximum, le plus ancien coché laissant sa place. Réservé aux chefs.", verbose_name='À la une de la confédération'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured_on_conf',
            field=models.BooleanField(default=False, help_text="Place l'article dans le diaporama d'accueil de cnt-so.org — le grand bandeau qui défile —, quel que soit le syndicat qui l'a écrit. Réservé aux chefs.", verbose_name='Diaporama de la confédération'),
        ),
    ]
