# Generated by Django 6.1.1 on 2026-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_image_block_position_largeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='in_carousel',
            field=models.BooleanField(default=False, help_text="Place l'article EN TÊTE du diaporama de VOTRE accueil — le grand bandeau qui défile. Seuls les articles cochés y figurent : sans aucun coché, pas de diaporama. 5 au maximum, le plus ancien laissant sa place. Décoché, l'article n'est pas perdu — il redescend dans la page.", verbose_name='Diaporama de mon syndicat'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='in_manchette',
            field=models.BooleanField(default=False, help_text="Place l'article EN TÊTE de la manchette de VOTRE accueil — les cartes situées sous le diaporama. Contrairement au diaporama, les récents illustrés la remplissent tout seuls autour des cochés : cocher sert à y maintenir un article. 6 au maximum, le plus ancien coché laissant sa place. Coché, il y figure même s'il est aussi au diaporama.", verbose_name='À la une de mon syndicat'),
        ),
    ]
