# Generated by Django 6.0.2 on 2026-04-29 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0015_category_redirect_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('stripe_account_id', models.CharField(blank=True, max_length=100, verbose_name='ID compte Stripe Connect')),
                ('stripe_onboarding_complete', models.BooleanField(default=False, verbose_name='Onboarding Stripe terminé')),
                ('price_mode', models.CharField(choices=[('libre', 'Prix libre'), ('fixed', 'Montant fixe')], default='libre', max_length=10, verbose_name='Mode de tarification')),
                ('fixed_amount_cents', models.PositiveIntegerField(blank=True, help_text='Ex: 500 pour 5,00€', null=True, verbose_name='Montant fixe (en centimes)')),
                ('allow_monthly', models.BooleanField(default=True, verbose_name='Autoriser mensuel')),
                ('allow_annual', models.BooleanField(default=True, verbose_name='Autoriser annuel')),
                ('allow_onetime', models.BooleanField(default=True, verbose_name='Autoriser ponctuel')),
                ('field_nom', models.BooleanField(default=True, verbose_name='Champ Nom')),
                ('field_prenom', models.BooleanField(default=True, verbose_name='Champ Prénom')),
                ('field_adresse', models.BooleanField(default=False, verbose_name='Champ Adresse')),
                ('field_ville', models.BooleanField(default=False, verbose_name='Champ Ville')),
                ('field_code_postal', models.BooleanField(default=False, verbose_name='Champ Code postal')),
                ('field_secteur_activite', models.BooleanField(default=False, verbose_name="Champ Secteur d'activité")),
                ('field_entreprise', models.BooleanField(default=False, verbose_name='Champ Entreprise')),
                ('field_telephone', models.BooleanField(default=False, verbose_name='Champ Téléphone')),
                ('lieu_defaut', models.CharField(blank=True, help_text='Lieu pré-rempli dans la zone signature (ex: Paris)', max_length=200, verbose_name='Lieu pré-rempli')),
                ('email_from', models.EmailField(blank=True, help_text='Adresse From pour les e-mails de confirmation (laissez vide pour utiliser la conf)', max_length=254, verbose_name='Adresse expéditeur')),
                ('email_contact', models.EmailField(blank=True, help_text='Adresse Reply-To dans les e-mails (adresse du syndicat)', max_length=254, verbose_name='Adresse de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulaire_adhesion', to='content.site', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': "Formulaire d'adhésion",
                'verbose_name_plural': "Formulaires d'adhésion",
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=200, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=200, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('secteur_activite', models.CharField(blank=True, max_length=200, verbose_name="Secteur d'activité")),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('lieu_signature', models.CharField(blank=True, max_length=200, verbose_name='Lieu de signature')),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='Date de signature')),
                ('certifie', models.BooleanField(default=False, verbose_name='Certifié exact')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Réponses champs custom')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Mensuelle'), ('annual', 'Annuelle'), ('onetime', 'Unique')], default='monthly', max_length=20, verbose_name='Périodicité')),
                ('payment_method', models.CharField(choices=[('stripe', 'Carte bancaire'), ('wero', 'Wero'), ('manuel', 'Manuel / Virement')], default='stripe', max_length=20, verbose_name='Moyen de paiement')),
                ('amount_cents', models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant (centimes)')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('actif', 'Actif'), ('annule', 'Annulé'), ('expire', 'Expiré'), ('manuel', 'Actif (manuel)')], default='pending', max_length=20, verbose_name='Statut')),
                ('newsletter_syndicat_done', models.BooleanField(default=False)),
                ('newsletter_regional_done', models.BooleanField(default=False)),
                ('newsletter_national_done', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('note_interne', models.TextField(blank=True, verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de première activation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='content.site', verbose_name='Syndicat')),
                ('formulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='adhesion.formulaireadhesion')),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prefix', models.CharField(help_text='Ex: 69 pour le Rhône, 75 pour Paris', max_length=5, unique=True, verbose_name='Préfixe code postal')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Libellé')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_geographiques', to='content.site', verbose_name='Site régional')),
            ],
            options={
                'verbose_name': 'Zone géographique',
                'verbose_name_plural': 'Zones géographiques',
                'ordering': ['code_prefix'],
            },
        ),
        migrations.CreateModel(
            name='ChampCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('slug', models.SlugField(help_text='Auto-généré depuis le libellé', max_length=200, verbose_name='Identifiant interne')),
                ('field_type', models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('select', 'Liste déroulante'), ('checkbox', 'Case à cocher')], default='text', max_length=20, verbose_name='Type de champ')),
                ('choices_text', models.TextField(blank=True, help_text='Pour type "liste déroulante" : une option par ligne', verbose_name='Options')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs_custom', to='adhesion.formulaireadhesion', verbose_name='Formulaire')),
            ],
            options={
                'verbose_name': 'Champ personnalisé',
                'verbose_name_plural': 'Champs personnalisés',
                'ordering': ['order'],
                'unique_together': {('formulaire', 'slug')},
            },
        ),
    ]
