# Generated by Django 4.2.11 on 2026-02-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_blog_id', models.IntegerField(help_text='blog_id WordPress', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('path', models.CharField(help_text='Path WordPress (ex: /rhone-alpes/)', max_length=100)),
                ('site_type', models.CharField(choices=[('main', 'Site principal'), ('regional', 'Union régionale'), ('sectoral', 'Syndicat sectoriel')], default='regional', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='wp_id',
            field=models.IntegerField(blank=True, help_text='ID WordPress original', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='wp_id',
            field=models.IntegerField(blank=True, help_text='ID WordPress original', null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='wp_id',
            field=models.IntegerField(blank=True, help_text='ID WordPress original', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
        migrations.AlterField(
            model_name='page',
            name='wp_id',
            field=models.IntegerField(blank=True, help_text='ID WordPress original', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.site'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='content.site'),
        ),
        migrations.AddField(
            model_name='media',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='content.site'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.site'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('site', 'slug'), ('site', 'wp_id')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('site', 'slug'), ('site', 'wp_id')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('site', 'slug'), ('site', 'wp_id')},
        ),
    ]
