# Generated by Django 6.0.2 on 2026-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_site_alter_article_slug_alter_article_wp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='wp_id',
            field=models.IntegerField(blank=True, help_text='ID WordPress original', null=True),
        ),
    ]
