# Generated by Django 6.0.2 on 2026-03-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='content.site', verbose_name='Site assigné'),
        ),
    ]
