# Generated by Django 6.0.2 on 2026-03-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_author_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('url', 'URL externe / personnalisée'), ('category', 'Catégorie du site'), ('site', 'Lien vers un site CNT'), ('article', 'Article du site'), ('page', 'Page du site')], default='url', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='opens_new_tab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='content.site'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_target', to='content.site'),
        ),
    ]
