# Generated by Django 6.0.2 on 2026-03-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_menuitem_site_linktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='content.site'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('site', 'slug')},
        ),
    ]
