# Generated by Django 6.0.2 on 2026-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_tag_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='sector',
            field=models.CharField(default='', max_length=200, verbose_name='Secteur professionnel'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='Objet'),
        ),
    ]
