# Generated by Django 6.0.2 on 2026-03-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contactmessage_phone_city_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='content.site', verbose_name='Site'),
        ),
    ]
