# Generated by Django 6.0.2 on 2026-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_add_site_to_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='external_url',
            field=models.URLField(blank=True, help_text='Si renseigné, les liens vers ce site pointent vers cette URL externe'),
        ),
    ]
