# Generated by Django 6.0.2 on 2026-03-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='agenda_url',
            field=models.URLField(blank=True, help_text="URL de l'agenda externe (ex: https://poitiers.demosphere.net)"),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('url', 'URL externe / personnalisée'), ('category', 'Catégorie du site'), ('site', 'Lien vers un site CNT'), ('article', 'Article du site'), ('page', 'Page du site'), ('contact', 'Formulaire de contact'), ('agenda', 'Agenda')], default='url', max_length=20),
        ),
    ]
