# Generated by Django 6.0.2 on 2026-03-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_site_agenda_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du sous-site (affiché dans le bandeau)', null=True, upload_to='sites/logos/'),
        ),
    ]
