# Generated by Django 6.0.2 on 2026-03-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='redirect_page',
            field=models.ForeignKey(blank=True, help_text="Si renseigné, redirige vers cette page au lieu d'afficher la liste des articles", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.page'),
        ),
    ]
