# Generated by Django 6.0.2 on 2026-05-28 21:57

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_category_redirect_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterarticle',
            name='newsletter',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_articles', to='content.newsletter'),
        ),
    ]
