# Generated by Django 6.0.2 on 2026-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_newsletterarticle_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Adresse email qui reçoit les messages du formulaire de contact', max_length=254, verbose_name='Email de contact'),
        ),
    ]
