# Generated by Django 6.0.2 on 2026-05-29 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_site_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Champs supplémentaires'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Secteur professionnel'),
        ),
        migrations.CreateModel(
            name='FormulaireContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('email_destination', models.EmailField(blank=True, help_text="Laissez vide pour utiliser l'email de contact du syndicat", max_length=254, verbose_name='Email de destination')),
                ('email_subject_prefix', models.CharField(blank=True, help_text='Ajouté au début du sujet (ex : [Contact CNT-SO])', max_length=100, verbose_name='Préfixe du sujet')),
                ('intro_text', models.TextField(blank=True, verbose_name="Texte d'introduction")),
                ('field_nom', models.BooleanField(default=True, verbose_name='Champ Nom')),
                ('field_telephone', models.BooleanField(default=False, verbose_name='Champ Téléphone')),
                ('field_ville', models.BooleanField(default=False, verbose_name='Champ Ville')),
                ('field_secteur', models.BooleanField(default=False, verbose_name='Champ Secteur')),
                ('field_objet', models.BooleanField(default=True, verbose_name='Champ Objet')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulaire_contact', to='content.site', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': 'Formulaire de contact',
                'verbose_name_plural': 'Formulaires de contact',
            },
        ),
        migrations.CreateModel(
            name='ChampContactCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('slug', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('select', 'Liste déroulante'), ('checkbox', 'Case à cocher')], default='text', max_length=20, verbose_name='Type')),
                ('choices_text', models.TextField(blank=True, help_text='Une option par ligne (pour les listes déroulantes)', verbose_name='Options')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs_custom', to='content.formulairecontact')),
            ],
            options={
                'verbose_name': 'Champ personnalisé',
                'verbose_name_plural': 'Champs personnalisés',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='formulaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='content.formulairecontact', verbose_name='Formulaire'),
        ),
    ]
