# Generated by Django 6.0.2 on 2026-05-29
#
# Stratégie (3 phases) :
# A - AlterField sans contrainte DB (db_constraint=False) : permet à SQLite de
#     recréer les tables sans valider les FK existantes (anciens content.Site PKs)
# B - RunPython : migration de données (site_id → SectionPage PK via slug)
# C - AlterField avec contrainte DB (db_constraint=True) : restaure les FK

import django.db.models.deletion
from django.db import migrations, models


def migrate_site_ids_to_section_page(apps, schema_editor):
    SectionPage = apps.get_model('cms', 'SectionPage')
    Site = apps.get_model('content', 'Site')

    sp_cache = {}
    for sp in SectionPage.objects.all():
        for slug in (sp.slug, sp.legacy_site_slug):
            if slug and slug not in sp_cache:
                sp_cache[slug] = sp.pk

    def sp_pk_for_old_id(old_id):
        try:
            site = Site.objects.get(pk=old_id)
            return sp_cache.get(site.slug)
        except Site.DoesNotExist:
            return None

    models_fields = [
        ('content', 'Author', 'site_id'),
        ('content', 'Category', 'site_id'),
        ('content', 'Tag', 'site_id'),
        ('content', 'Media', 'site_id'),
        ('content', 'Article', 'site_id'),
        ('content', 'Page', 'site_id'),
        ('content', 'ContactMessage', 'site_id'),
        ('content', 'FormulaireContact', 'site_id'),
        ('content', 'Subscriber', 'site_id'),
        ('content', 'Newsletter', 'site_id'),
        ('content', 'MenuItem', 'site_id'),
        ('content', 'MenuItem', 'target_site_id'),
    ]

    for app_label, model_name, field_id in models_fields:
        Model = apps.get_model(app_label, model_name)
        mapping = {}   # obj_pk → new SectionPage pk
        to_nullify = []  # obj_pk → no SectionPage found, must be NULL
        for obj in Model.objects.filter(**{f'{field_id}__isnull': False}):
            new_pk = sp_pk_for_old_id(getattr(obj, field_id))
            if new_pk is not None:
                mapping[obj.pk] = new_pk
            else:
                to_nullify.append(obj.pk)
        # 1. Nullifier tout (mapping + orphelins) pour éviter violations UNIQUE
        all_pks = list(mapping.keys()) + to_nullify
        if all_pks:
            Model.objects.filter(pk__in=all_pks).update(**{field_id: None})
        # 2. Remettre les PKs mappés
        for obj_pk, new_pk in mapping.items():
            Model.objects.filter(pk=obj_pk).update(**{field_id: new_pk})


class Migration(migrations.Migration):
    # DDL + DML dans la même migration : incompatible avec les transactions PostgreSQL
    atomic = False

    dependencies = [
        ('cms', '0002_sectionpage_contact_email_wp_blog_id_path'),
        ('content', '0018_formulairecontact_champcontactcustom'),
    ]

    operations = [
        # ── A : sans contrainte DB ─────────────────────────────────────────────
        migrations.AlterField(
            model_name='article', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='articles',
                db_constraint=False),
        ),
        migrations.AlterField(
            model_name='author', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='team_members',
                verbose_name='Site assigné', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='category', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='categories',
                db_constraint=False),
        ),
        migrations.AlterField(
            model_name='contactmessage', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages',
                verbose_name='Site', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='formulairecontact', name='site',
            field=models.OneToOneField('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='formulaire_contact',
                verbose_name='Syndicat', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='media', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='medias',
                db_constraint=False),
        ),
        migrations.AlterField(
            model_name='menuitem', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='menu_items',
                db_constraint=False),
        ),
        migrations.AlterField(
            model_name='menuitem', name='target_site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_target',
                db_constraint=False),
        ),
        migrations.AlterField(
            model_name='newsletter', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='newsletters',
                verbose_name='Site', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='page', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='pages',
                db_constraint=False),
        ),
        migrations.AlterField(
            model_name='subscriber', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscribers',
                verbose_name='Site', db_constraint=False),
        ),
        migrations.AlterField(
            model_name='tag', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='tags',
                db_constraint=False),
        ),

        # ── B : migration de données ───────────────────────────────────────────
        migrations.RunPython(migrate_site_ids_to_section_page, migrations.RunPython.noop),

        # ── C : restaurer les contraintes FK ──────────────────────────────────
        migrations.AlterField(
            model_name='article', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='articles'),
        ),
        migrations.AlterField(
            model_name='author', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='team_members',
                verbose_name='Site assigné'),
        ),
        migrations.AlterField(
            model_name='category', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='categories'),
        ),
        migrations.AlterField(
            model_name='contactmessage', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages',
                verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='formulairecontact', name='site',
            field=models.OneToOneField('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='formulaire_contact',
                verbose_name='Syndicat'),
        ),
        migrations.AlterField(
            model_name='media', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='medias'),
        ),
        migrations.AlterField(
            model_name='menuitem', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='menu_items'),
        ),
        migrations.AlterField(
            model_name='menuitem', name='target_site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_target'),
        ),
        migrations.AlterField(
            model_name='newsletter', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='newsletters',
                verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='page', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='pages'),
        ),
        migrations.AlterField(
            model_name='subscriber', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscribers',
                verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='tag', name='site',
            field=models.ForeignKey('cms.sectionpage', blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE, related_name='tags'),
        ),
    ]
