# Generated by Django 6.0.2 on 2026-05-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_migrate_site_fks_to_sectionpage'),
        ('adhesion', '0002_migrate_site_fk_to_sectionpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
