# Generated by Django 6.0.2 on 2026-06-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='formulairecontact',
            name='field_prenom',
            field=models.BooleanField(default=False, verbose_name='Champ Prénom'),
        ),
    ]
