# Generated by Django 6.0.7 on 2026-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_cleanup_section_menu_contact_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='ovh_list',
            field=models.CharField(blank=True, help_text='Liste OVH sur laquelle cet abonné a été inscrit (répartition automatique quand un site a plusieurs listes)', max_length=100, verbose_name='Liste OVH'),
        ),
    ]
