# Generated by Django 6.0.7 on 2026-08-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_remove_articlepage_author_user_and_more'),
        ('content', '0028_subscriber_ovh_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permanence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(help_text="Tel qu'affiché en titre de fiche, ex. « CNT-SO 13 — Marseille ».", max_length=120)),
                ('adresse', models.CharField(help_text="Rue, code postal, ville. Ajoutez le métro ou l'arrêt si utile.", max_length=300)),
                ('horaires', models.CharField(blank=True, help_text='Ex. « Lun–Ven 09h–12h / 14h–17h ». Laisser vide si variable.', max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('telephone_secondaire', models.CharField(blank=True, help_text='Second numéro, si la permanence en annonce deux.', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lien', models.URLField(blank=True, help_text="Page ou site du syndicat. Laisser vide s'il n'y en a pas : le bouton disparaît alors.")),
                ('libelle_lien', models.CharField(blank=True, default='En savoir plus', max_length=60, verbose_name='Libellé du bouton')),
                ('order', models.PositiveIntegerField(default=0, help_text="Les plus petits nombres s'affichent en premier.", verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Affichée')),
                ('site', models.ForeignKey(blank=True, help_text='Le syndicat qui tient cette permanence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanences', to='cms.sectionpage', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': 'Permanence juridique',
                'verbose_name_plural': 'Permanences juridiques',
                'ordering': ['order', 'ville'],
            },
        ),
    ]
