# Generated by Django 6.0.7 on 2026-08-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_sectionpage_feed_etag_sectionpage_feed_last_sync_and_more'),
        ('content', '0029_permanence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(help_text="Identifiant de l'entrée dans le flux : ce qui distingue un article republié d'un nouvel article.", max_length=500)),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('url', models.URLField(max_length=500, verbose_name='Lien')),
                ('published_at', models.DateTimeField(verbose_name='Date de publication')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_articles', to='cms.sectionpage', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': "Article d'un site externe",
                'verbose_name_plural': 'Articles des sites externes',
                'ordering': ['-published_at'],
                'unique_together': {('section', 'guid')},
            },
        ),
    ]
