# Generated by Django 6.0.7 on 2026-08-17 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_sectionpage_feed_etag_sectionpage_feed_last_sync_and_more'),
        ('content', '0030_externalarticle'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheSyndicat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Le nom du champ de syndicalisation, ex. « Nettoyage ».', max_length=120)),
                ('description', models.CharField(blank=True, help_text='Une ligne pour dire ce que le champ recouvre, ex. « Hôtels, restaurants, tourisme… ».', max_length=300)),
                ('image_url', models.CharField(blank=True, help_text="Chemin d'un visuel de l'ancien site, utilisé faute d'image ci-dessus. Renseigné par l'import, à ne pas saisir à la main.", max_length=500, verbose_name='Visuel hérité')),
                ('url', models.CharField(blank=True, help_text='À défaut de catégorie ou de syndicat : une adresse libre.', max_length=500, verbose_name='Autre adresse')),
                ('order', models.PositiveIntegerField(default=0, help_text="Les plus petits nombres s'affichent en premier.", verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Affichée')),
                ('categorie', models.ForeignKey(blank=True, help_text='La carte mène à cette rubrique du site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_syndicats', to='cms.cmscategory', verbose_name='Catégorie')),
                ('image', models.ForeignKey(blank=True, help_text="L'affiche est montrée entière, jamais recadrée.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Visuel')),
                ('site', models.ForeignKey(blank=True, help_text="Le site dont c'est l'annuaire. La confédération, sauf si un syndicat veut le sien.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_syndicats', to='cms.sectionpage', verbose_name='Site propriétaire')),
                ('site_cible', models.ForeignKey(blank=True, help_text="La carte mène à l'accueil de ce syndicat.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_pointant_ici', to='cms.sectionpage', verbose_name='Syndicat')),
            ],
            options={
                'verbose_name': 'Fiche syndicat',
                'verbose_name_plural': 'Fiches syndicats',
                'ordering': ['order', 'titre'],
            },
        ),
    ]
