# Generated by Django 6.0.7 on 2026-08-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_fichesyndicat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.CharField(choices=[('main', 'Menu principal'), ('footer', 'Menu pied de page')], default='main', max_length=20),
        ),
    ]
