# Generated by Django 6.0.7 on 2026-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_alter_menuitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterarticle',
            name='rubrique',
            field=models.CharField(blank=True, choices=[('campagne', 'Campagnes'), ('actu-syndicale', 'Actu syndicale'), ('actu-generale', 'Actu générale'), ('droits', 'Nos droits'), ('international', 'International')], help_text="La section de la newsletter où ranger cet article. Laisser vide place l'article en tête, sans titre de section — ce que font les syndicats, qui n'ont pas de rubriques.", max_length=30, verbose_name='Rubrique'),
        ),
    ]
