# Generated by Django 6.0.7 on 2026-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_newsletterarticle_rubrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterarticle',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Dans quel ordre au sein de la rubrique. Les plus petits nombres passent en premier ; à égalité, l'ordre de saisie décide.", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='newsletterarticle',
            name='rubrique',
            field=models.CharField(blank=True, choices=[('', 'Sans rubrique — en tête de la lettre'), ('campagne', 'Campagnes'), ('actu-syndicale', 'Actu syndicale'), ('actu-generale', 'Actu générale'), ('droits', 'Nos droits'), ('international', 'International')], help_text="Plusieurs articles peuvent partager la même rubrique : ajoutez-en autant que voulu et donnez-leur la même. Sans rubrique, l'article s'affiche en tête, avant toute section.", max_length=30, verbose_name='Rubrique'),
        ),
    ]
