# Generated by Django 6.0.7 on 2026-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_newsletter_rubriques_porteuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrubrique',
            name='rubrique',
            field=models.CharField(blank=True, choices=[('', 'Sans titre de section'), ('campagne', 'Campagnes'), ('actu-syndicale', 'Actu syndicale'), ('actu-generale', 'Actu générale'), ('droits', 'Nos droits'), ('international', 'International')], help_text="Le titre de section affiché dans l'e-mail. Sans titre, les articles ouvrent la lettre, avant toute section.", max_length=30, verbose_name='Rubrique'),
        ),
    ]
