# Generated by Django 6.1.1 on 2026-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_libelle_rubrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sending', 'Envoi en cours'), ('sent', 'Envoyée')], default='draft', max_length=20),
        ),
    ]
