# Generated by Django 6.1.1 on 2026-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_newsletter_statut_envoi_en_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='envoi_commence_le',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
