# Generated by Django 6.1.1 on 2026-09-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_newsletter_envoi_commence_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('titre', 'Titre de sous-menu (sans lien)'), ('url', 'URL externe / personnalisée'), ('category', 'Catégorie du site'), ('site', 'Lien vers un site CNT'), ('article', 'Article du site'), ('page', 'Page du site'), ('contact', 'Formulaire de contact'), ('agenda', 'Agenda')], default='url', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="L'entrée dont celle-ci est une sous-entrée. Laissez vide pour le premier niveau du menu. Trois niveaux au plus ; l'ordre se règle ensuite en glissant dans « Menus ».", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem', verbose_name='Ranger sous'),
        ),
    ]
